version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ClearDent-Frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/ClearDent-Backend"
    schedule:
      interval: "weekly"
